// @ts-check
const fs = require('fs');
const path = require('path');
const {themes} = require('prism-react-renderer');

const lightCodeTheme = themes.github;
const darkCodeTheme = themes.palenight;

// Obol-coloured code blocks
const obolDarkCodeTheme = {
  ...darkCodeTheme,
  plain: {color: '#bfc7d5', backgroundColor: '#16282d'},
};

// Legacy-path redirects generated by scripts (see scripts/generated/redirects.json).
const redirectsFile = path.join(__dirname, 'scripts/generated/redirects.json');
/** @type {{from: string, to: string}[]} */
const legacyRedirects = fs.existsSync(redirectsFile)
  ? JSON.parse(fs.readFileSync(redirectsFile, 'utf8'))
  : [];

// Deployment target.
// - Production (default): https://docs.obol.org at /
// - Preview (DEPLOY_PREVIEW=true): https://obolnetwork.github.io/obol-docs/
//   so the site can be shared before DNS points docs.obol.org here.
const isPreview = process.env.DEPLOY_PREVIEW === 'true';
const siteUrl = isPreview ? 'https://obolnetwork.github.io' : 'https://docs.obol.org';
const baseUrl = process.env.BASE_URL ?? (isPreview ? '/obol-docs/' : '/');

// The released version served at the site root. Cut a new release with
// `yarn version <vX.Y>` (docusaurus docs:version) — the newest entry in
// versions.json automatically becomes the root-served version; older
// releases stay reachable at /<version>/ with an "unmaintained" banner.
const versions = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'versions.json'), 'utf8'),
);
const lastVersion = versions[0];

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Obol Documentation',
  tagline:
    'Run Ethereum validators that are more secure, resilient, and performant with Distributed Validator Technology.',
  url: siteUrl,
  baseUrl,
  staticDirectories: ['static', ...(isPreview ? [] : ['static-prod'])],
  trailingSlash: false,
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',
  markdown: {
    // .md files are parsed as CommonMark (tolerant of GitBook-imported HTML),
    // .mdx files as MDX (used where docs need Tabs / components).
    format: 'detect',
    mdx1Compat: {
      // Keep `### Heading {#custom-id}` working in .mdx files (v4 future
      // flag turns this off by default; our GitBook import relies on it to
      // preserve the live site's anchor ids).
      headingIds: true,
      comments: false,
      admonitions: false,
    },
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },
  future: {
    v4: true,
    faster: true,
  },
  favicon: 'img/favicon.ico',
  organizationName: 'ObolNetwork',
  projectName: 'obol-docs',

  headTags: [
    {
      tagName: 'script',
      attributes: {type: 'application/ld+json'},
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebSite',
        name: 'Obol Documentation',
        url: 'https://docs.obol.org',
        publisher: {
          '@type': 'Organization',
          name: 'Obol',
          url: 'https://obol.org',
          logo: 'https://docs.obol.org/img/ObolIconLight.svg',
        },
      }),
    },
    {
      tagName: 'link',
      attributes: {rel: 'preconnect', href: 'https://fonts.googleapis.com'},
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'preconnect',
        href: 'https://fonts.gstatic.com',
        crossorigin: 'anonymous',
      },
    },
    {
      tagName: 'link',
      attributes: {
        rel: 'stylesheet',
        href: 'https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700;800&family=Figtree:ital,wght@0,400;0,500;0,600;0,700;1,400&family=IBM+Plex+Mono:wght@400;500;600&display=swap',
      },
    },
  ],

  plugins: [
    [
      '@docusaurus/plugin-client-redirects',
      {
        fromExtensions: ['html', 'htm'],
        redirects: legacyRedirects,
      },
    ],
    './plugins/llms-txt',
  ],

  themes: [
    /** @type {any} */ ([
      '@easyops-cn/docusaurus-search-local',
      /** @type {import("@easyops-cn/docusaurus-search-local").PluginOptions} */
      ({
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/',
        highlightSearchTermsOnTargetPage: true,
        explicitSearchResultPath: true,
      }),
    ]),
  ],

  presets: [
    [
      '@docusaurus/preset-classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          routeBasePath: '/',
          sidebarPath: './sidebars.js',
          editUrl: ({versionDocsDirPath, docPath}) =>
            `https://github.com/ObolNetwork/obol-docs/edit/main/${versionDocsDirPath}/${docPath}`,
          lastVersion,
          versions: {
            current: {
              label: 'next 🚧',
              path: 'next',
              banner: 'unreleased',
              noIndex: true,
            },
            [lastVersion]: {
              label: lastVersion,
              path: '',
              banner: 'none',
            },
          },
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
        gtag: {
          trackingID: 'G-DTT2S469C4',
          anonymizeIP: true,
        },
        sitemap: {
          lastmod: 'date',
          changefreq: null,
          priority: null,
          ignorePatterns: ['/next/**'],
        },
      }),
    ],
    [
      'redocusaurus',
      {
        specs: [
          {
            // Vendored copy of https://api.obol.tech/docs-json so builds
            // never depend on the live API. Refresh with:
            //   node scripts/update-api-spec.mjs
            spec: 'static/openapi/obol-api.json',
            route: '/api/',
            layout: {
              title: 'Obol API Reference',
              description:
                'REST API for creating and managing Distributed Validator clusters, built by Obol.',
            },
          },
        ],
        theme: {
          primaryColor: '#16968E',
          theme: {
            colors: {
              http: {
                get: '#16968e',
                put: '#9167e4',
                post: '#2fe4ab',
                delete: '#dd603c',
              },
            },
            rightPanel: {
              backgroundColor: '#16282d',
            },
          },
        },
      },
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      image: 'img/obol-docs-og.png',
      colorMode: {
        defaultMode: 'dark',
        disableSwitch: false,
        respectPrefersColorScheme: true,
      },
      docs: {
        sidebar: {
          hideable: true,
          autoCollapseCategories: true,
        },
      },
      navbar: {
        title: 'Obol Docs',
        logo: {
          alt: 'Obol Logo',
          src: '/img/ObolIconDark.svg',
          srcDark: '/img/ObolIconLight.svg',
        },
        items: [
          {
            type: 'doc',
            docId: 'README',
            position: 'left',
            label: 'Documentation',
          },
          {
            type: 'doc',
            docId: 'obol-stack/README',
            position: 'left',
            label: 'Obol Stack',
          },
          {
            type: 'doc',
            docId: 'sdk/index',
            position: 'left',
            label: 'SDK',
          },
          {
            to: '/api/',
            position: 'left',
            label: 'API',
          },
          {
            type: 'docsVersionDropdown',
            position: 'right',
          },
          {
            href: 'https://launchpad.obol.org',
            label: 'Launchpad',
            position: 'right',
            className: 'navbar-cta',
          },
          {
            href: 'https://github.com/ObolNetwork',
            position: 'right',
            className: 'header-github-link',
            'aria-label': 'GitHub',
          },
        ],
      },
      footer: {
        style: 'dark',
        logo: {
          alt: 'Obol Logo',
          src: '/img/ObolLineWhite.svg',
          width: 110,
          href: 'https://obol.org/',
        },
        links: [
          {
            title: 'Get Started',
            items: [
              {label: 'Quickstart', to: '/run-a-dv/start/quickstart_overview'},
              {label: 'DV Launchpad', href: 'https://launchpad.obol.org'},
              {label: 'Obol Stack', to: '/obol-stack/obol-stack'},
              {label: 'Deployment Best Practices', to: '/run-a-dv/prepare/deployment-best-practices'},
            ],
          },
          {
            title: 'Build',
            items: [
              {label: 'API Reference', to: '/api/'},
              {label: 'SDK', to: '/sdk/index'},
              {label: 'Charon CLI', to: '/learn/charon/charon-cli-reference'},
              {label: 'GitHub', href: 'https://github.com/ObolNetwork'},
            ],
          },
          {
            title: 'Collective',
            items: [
              {label: 'Obol.org', href: 'https://obol.org'},
              {label: 'Discord', href: 'https://discord.gg/obol'},
              {label: 'X / Twitter', href: 'https://x.com/Obol_Collective'},
              {label: 'Blog', href: 'https://blog.obol.org'},
            ],
          },
          {
            title: 'Resources',
            items: [
              {label: 'Status', href: 'https://status.obol.org'},
              {label: 'Security', to: '/advanced-and-troubleshooting/security/overview'},
              {label: 'Bug Bounty', to: '/advanced-and-troubleshooting/security/bug-bounty'},
              {label: 'llms.txt', to: 'pathname:///llms.txt', target: '_blank'},
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Obol Association.`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: obolDarkCodeTheme,
        additionalLanguages: [
          'bash',
          'json',
          'yaml',
          'toml',
          'solidity',
          'docker',
        ],
      },
      metadata: [
        {name: 'twitter:card', content: 'summary_large_image'},
        {name: 'twitter:site', content: '@Obol_Collective'},
        {property: 'og:type', content: 'website'},
        {
          name: 'keywords',
          content:
            'Obol, Distributed Validators, DVT, Ethereum staking, Charon, Obol Stack, validator middleware',
        },
      ],
    }),
};

module.exports = config;
