/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  apiSidebar: [
    {
      "type": "doc",
      "id": "sdk/index",
      "label":"Intro"
    },
    {
      "type": "category",
      "label": "Enumerations",
      "collapsible": true,
      "collapsed": true,
      "items": [
        {
          "type": "doc",
          "id": "sdk/enumerations/FORK_MAPPING",
        },
      ],
    },
    {
      "type": "category",
      "label": "Classes",
      "collapsible": true,
      "collapsed": true,
      "items": [
        {
          "type": "doc",
          "id": "sdk/classes/Client",
        },
      ],
    },
    {
      "type": "category",
      "label": "Interfaces",
      "collapsible": true,
      "collapsed": true,
      "items": [
        {
          "type": "doc",
          "id": "sdk/interfaces/ClusterDefintion",
        },
      ],
    },
    {
      "type": "category",
      "label": "Type-Aliases",
      "collapsible": true,
      "collapsed": true,
      "items": [
        {
          "type": "doc",
          "id": "sdk/type-aliases/BuilderRegistration",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/BuilderRegistrationMessage",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/ClusterCreator",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/ClusterLock",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/ClusterOperator",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/ClusterPayload",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/ClusterValidator",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/DepositData",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/DistributedValidator",
        },
        {
          "type": "doc",
          "id": "sdk/type-aliases/OperatorPayload",
        },
      ],
    },
    {
      "type": "category",
      "label": "Functions",
      "collapsible": true,
      "collapsed": true,
      "items": [
        {
          "type": "doc",
          "id": "sdk/functions/validateClusterLock",
        },
      ],
    },
  ],

  // Add custom sidebar for "api" folder

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
