name: Test deployment

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-typecheck:
    name: Build and typecheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "24"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Typecheck
        run: yarn typecheck

      - name: Build site
        run: yarn build
